# GaussianNB

In [14]:
import pandas as pd # data processing, CSV file
#pd: allows to use pandas functions pd.KAZA 
import numpy as nm  #Generate matrices
import matplotlib.pyplot as mtp  # for data visualization purposes
from sklearn.metrics import accuracy_score, classification_report 
# accuracy_score: function computes  accuracy 
# classification_report: performance evaluation metric in machine learning. It is used to show the precision, recall, F1 Score, and support of your trained classification model.
from sklearn.preprocessing import OneHotEncoder,StandardScaler
# OneHotEncoder string values zai letter column kda 
# StandardScaler to scale your data. twsee3 el data 

In [15]:
DataSSet = pd.read_csv('letter-recognition.csv') #function help in raeding cvs file b access el dataset y3ne
DataSSet.head() #function is used to get the first n rows.

letter  xbox   ybox   width   height  onpix   xbar   ybar   x2bar  y2bar   \
0      T      2      8       3       5       1      8     13      0       6   
1      I      5     12       3       7       2     10      5      5       4   
2      D      4     11       6       8       6     10      6      2       6   
3      N      7     11       6       6       3      5      9      4       6   
4      G      2      1       3       1       1      8      6      6       6   

   xybar   x2ybar  xy2bar  xedge   xedgey  yedge   yedgex  
0       6      10       8       0       8       0       8  
1      13       3       9       2       8       4      10  
2      10       3       7       3       7       3       9  
3       4       4      10       6      10       2       8  
4       6       5       9       1       7       5      10

In [16]:
DataSSet.shape  #17 column 20001 row 

(20000, 17)

In [17]:
# Importing ll data set
y = DataSSet.iloc[:,0].values
X = DataSSet.iloc[:,1:17].values
# Splitting the dataset into the Training set and Test set  

from sklearn.model_selection import train_test_split  
x_train, x_test, y_train, y_test = train_test_split(X, y, test_size = 0.15, random_state =0) 
print(DataSSet.iloc[:,1:17].values)

[[ 2  8  3 ...  8  0  8]
 [ 5 12  3 ...  8  4 10]
 [ 4 11  6 ...  7  3  9]
 ...
 [ 6  9  6 ... 12  2  4]
 [ 2  3  4 ...  9  5  8]
 [ 4  9  6 ...  7  2  8]]


In [18]:
from sklearn.naive_bayes import GaussianNB
classifier = GaussianNB()
# rule el probability 
classifier.fit(x_train, y_train)
# perform the calculation on the feature values of input data and fit this calculation to the transformer.

GaussianNB()

In [19]:
y_pred  =  classifier.predict(x_test)
from sklearn.metrics import confusion_matrix,accuracy_score
cm = confusion_matrix(y_test, y_pred)
ac = accuracy_score(y_test,y_pred)
print("Accuracy:" , ac)

Accuracy: 0.6513333333333333


In [20]:
print(classification_report(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))
Accuracy = round((accuracy_score(y_test, y_pred) * 100))
from sklearn.metrics import confusion_matrix,accuracy_score
print("Accuracy : " , Accuracy , "%")

              precision    recall  f1-score   support

           A       0.84      0.86      0.85       107
           B       0.46      0.60      0.52       113
           C       0.76      0.75      0.75       130
           D       0.68      0.71      0.70       128
           E       0.57      0.41      0.48       106
           F       0.69      0.74      0.71       121
           G       0.63      0.51      0.56       144
           H       0.57      0.44      0.50        95
           I       0.49      0.76      0.60        88
           J       0.85      0.75      0.79       110
           K       0.40      0.42      0.41       103
           L       0.98      0.81      0.89       122
           M       0.70      0.91      0.79       141
           N       0.83      0.71      0.76       110
           O       0.49      0.73      0.59       105
           P       0.88      0.69      0.77       124
           Q       0.52      0.58      0.55       108
           R       0.53    

# MultinomialNB

In [21]:
from sklearn.naive_bayes import MultinomialNB

In [22]:
clf = MultinomialNB()
model = clf.fit(X, y)

In [23]:
print(classification_report(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))
y_pred =clf.predict(x_test)
acc_score = accuracy_score(y_test, y_pred)
acc_score = round((accuracy_score(y_test, y_pred) * 100))
from sklearn.metrics import confusion_matrix,accuracy_score
print("Accuracy : " , acc_score , "%")

              precision    recall  f1-score   support

           A       0.84      0.86      0.85       107
           B       0.46      0.60      0.52       113
           C       0.76      0.75      0.75       130
           D       0.68      0.71      0.70       128
           E       0.57      0.41      0.48       106
           F       0.69      0.74      0.71       121
           G       0.63      0.51      0.56       144
           H       0.57      0.44      0.50        95
           I       0.49      0.76      0.60        88
           J       0.85      0.75      0.79       110
           K       0.40      0.42      0.41       103
           L       0.98      0.81      0.89       122
           M       0.70      0.91      0.79       141
           N       0.83      0.71      0.76       110
           O       0.49      0.73      0.59       105
           P       0.88      0.69      0.77       124
           Q       0.52      0.58      0.55       108
           R       0.53    

# BernoulliNB

In [24]:
from sklearn.naive_bayes import BernoulliNB 

In [25]:
clf = BernoulliNB()
model = clf.fit(X, y)

In [26]:
print(classification_report(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))
y_pred =clf.predict(x_test)
acc_score = accuracy_score(y_test, y_pred)
acc_score = round((accuracy_score(y_test, y_pred) * 100))
from sklearn.metrics import confusion_matrix,accuracy_score
print("Accuracy : " , acc_score , "%")

              precision    recall  f1-score   support

           A       0.65      0.90      0.75       107
           B       0.40      0.66      0.50       113
           C       0.45      0.72      0.55       130
           D       0.62      0.61      0.62       128
           E       0.50      0.33      0.40       106
           F       0.60      0.71      0.65       121
           G       0.42      0.31      0.35       144
           H       0.18      0.04      0.07        95
           I       0.61      0.76      0.68        88
           J       0.80      0.64      0.71       110
           K       0.23      0.22      0.22       103
           L       0.87      0.69      0.77       122
           M       0.68      0.69      0.68       141
           N       0.52      0.65      0.57       110
           O       0.63      0.63      0.63       105
           P       0.80      0.61      0.69       124
           Q       0.48      0.65      0.55       108
           R       0.43    